FinalMVC/ViewComponents/FooterViewComponent.cs
using FinalMVC.DAL;
using FinalMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalMVC.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public FooterViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }


        public IViewComponentResult Invoke()
        {
            var footer = _dbContext.Footer.Include(x => x.GetInTouch).Include(x => x.Information).Include(x => x.SocialMedia).Include(x => x.UsefulLinks).FirstOrDefault();

            return View(footer);
        }
    }
}

FinalMVC/ViewComponents/HeaderViewComponent.cs
using FinalMVC.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinalMVC.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public HeaderViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            var header = _dbContext.Header.Include(x => x.Navigation).FirstOrDefault();

            return View(header);
        }
    }
}

FinalMVC/Views/Shared/_BlogPartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Blog>


@foreach (var item in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-blog mb-60">
            <div class="blog-img">
                <a asp-controller="blog" asp-action="details" asp-route-id="@item.Id"><img src="~/img/blog/@item.ImageUrl" alt="blog"></a>
                <div class="blog-hover">
                    <i class="fa fa-link"></i>
                </div>
            </div>
            <div class="blog-content">
                <div class="blog-top">
                    <p>@item.CreatedBy  /  @item.Date  /  <i class="fa fa-comments-o"></i>@item.CommentCount</p>
                </div>
                <div class="blog-bottom">
                    <h2><a asp-controller="blog" asp-action="details" asp-route-id="@item.Id">@item.Title </a></h2>
                    <a asp-controller="blog" asp-action="details" asp-route-id="@item.Id">read more</a>
                </div>
            </div>
        </div>
    </div>
}

FinalMVC/Views/Shared/_CoursePartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Course>

@foreach (var item in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-course mb-70">
            <div class="course-img">
                <a asp-controller="course" asp-action="details" asp-route-id="id">
                    <img src="~/img/course/@item.ImageUrl" alt="course">
                    <div class="course-hover">
                        <i class="fa fa-link"></i>
                    </div>
                </a>
            </div>
            <div class="course-content">
                <h3><a asp-controller="course" asp-action="details" asp-route-id="@item.Id">@item.Title</a></h3>
                <p>@item.Description</p>
                <a asp-controller="course" asp-action="details" asp-route-id="@item.Id" class="default-btn">read more</a>
            </div>
        </div>
    </div>
}

FinalMVC/Views/Shared/_EventPartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Event>

@foreach (var item in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-event mb-60">
            <div class="event-img">
                <a href="event-details.html">
                    <img src="~/img/event/@item.ImageUrl" alt="event">
                    <div class="course-hover">
                        <i class="fa fa-link"></i>
                    </div>
                </a>
                <div class="event-date">
                    @Html.Raw(item.Date)
                </div>
            </div>
            <div class="event-content text-left">
                <h4><a href="event-details.html">@item.Title</a></h4>
                <ul>
                    <li><span>time:</span> @item.Time</li>
                    <li><span>venue</span>@item.Location</li>
                </ul>
                <div class="event-content-right">
                    <a a asp-controller="event" asp-action="details" asp-route-id="@item.Id" class="default-btn">join now</a>
                </div>
            </div>
        </div>
    </div>
}

FinalMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<!-- Mirrored from demo.devitems.com/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:44:02 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/meanmenu.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/et-line-icon.css">
    <link rel="stylesheet" href="~/css/reset.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->
    @await Component.InvokeAsync("Header")
    <!-- Header Area End -->

    @RenderBody()

    <!-- Subscribe Start -->
    @await Component.InvokeAsync("Subscribe")
    <!-- Subscribe End -->

    <!-- Footer Start -->
    @await Component.InvokeAsync("Footer")
    <!-- Footer End -->

    <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.meanmenu.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/ajax-mail.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
</body>

<!-- Mirrored from demo.devitems.com/eduhome/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:44:03 GMT -->
</html>

FinalMVC/Views/Shared/_NoticePartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Notice>

@foreach (var item in Model)
{
    <div class="single-notice-left mb-23 pb-20">
        <h4>@item.PostDate</h4>
        <p>@item.Text </p>
    </div>
}

FinalMVC/Views/Shared/_SearchedCoursePartial.cshtml
@using FinalMVC.DAL.Entities
@model List<Course>

@foreach (var item in Model)
{
    <li>
        <a asp-controller="course" asp-action="details" asp-route-id="@item.Id">
            @item.Title
        </a>
    </li>

}

FinalMVC/Views/Shared/_SearchedTeacherPartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Teacher>

@foreach (var item in Model)
{
    <li>
        <a asp-controller="teacher" asp-action="details" asp-route-id="@item.Id">
            @item.FullName
        </a>
    </li>
}

FinalMVC/Views/Shared/_TeacherPartial.cshtml
@using FinalMVC.DAL.Entities;
@model List<Teacher>

@foreach (var teacher in Model)
{
    <div class="col-md-3 col-sm-4 col-xs-12">
        <div class="single-teacher mb-45">
            <div class="single-teacher-img">
                <a a asp-controller="teacher" asp-action="details" asp-route-id="@teacher.Id"><img src="~/img/teacher/@teacher.ImageUrl" alt="teacher"></a>
            </div>
            <div class="single-teacher-content text-center">
                <h2><a asp-controller="teacher" asp-action="details" asp-route-id="@teacher.Id">@teacher.FullName</a></h2>
                <h4>@teacher.KindOfActivity</h4>
                <ul>
                    <li><a href="@teacher.Facebook"><i class="zmdi zmdi-facebook"></i></a></li>
                    <li><a href="@teacher.Pinterest"><i class="zmdi zmdi-pinterest"></i></a></li>
                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                    <li><a href="@teacher.Twitter"><i class="zmdi zmdi-twitter"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
}